language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - mkdir ./temp
  - mysql -e 'create database kz_test;'

script: ./vendor/bin/tester -j 1 ./tests